#ifndef _MARVELL_H
#define _MARVELL_H

/* Marvell 88E6020 registers */
#define SMICOMMAND_SMIBUSY 0x8000
#define SMICOMMAND_MODESMI 0x1000
#define SMICOMMAND_READ    0x0800
#define SMICOMMAND_WRITE   0x0400

#define SMIPHYCOMMAND      0x18
#define SMIPHYDATA         0x19

#define SMIGLOBAL2         0x17

/* These + port number */
#define PHY_REG_BASE       0x10
#define SW_REG_BASE        0x18

#define PHY_CONTROL        0x00
#define PHY_CONTROL_SWRESET              0x8000
#define PHY_CONTROL_LOOPBACK             0x4000
#define PHY_CONTROL_SPEED10              0x0000
#define PHY_CONTROL_SPEED100             0x2000
#define PHY_CONTROL_ANEGDISABLE          0x0000
#define PHY_CONTROL_ANEGENABLE           0x1000
#define PHY_CONTROL_NORMALOPERATION      0x0000
#define PHY_CONTROL_PWRDWN               0x0800
#define PHY_CONTROL_ISOLATE              0x0400
#define PHY_CONTROL_RESTARTANEG          0x0200
#define PHY_CONTROL_DUPLEXHALF           0x0000
#define PHY_CONTROL_DUPLEXFULL           0x0100
#define PHY_CONTROL_COLTESTDISABLE       0x0000
#define PHY_CONTROL_COLTESTENABLE        0x0080
#define PHY_CONTROL_UNIDIRECTIONALENABLE 0x0020

#define SW_PORT_STATUS     0x00
#define SW_PORT_STATUS_LINKPAUSE                   0x8000
#define SW_PORT_STATUS_MYPAUSE                     0x4000
#define SW_PORT_STATUS_RESOLVED                    0x2000
#define SW_PORT_STATUS_LINK                        0x1000
#define SW_PORT_STATUS_PORTMODEMASK                0x0f00
#define SW_PORT_STATUS_PORTMODE_10HALF             0x0800
#define SW_PORT_STATUS_PORTMODE_100HALF            0x0900
#define SW_PORT_STATUS_PORTMODE_10FULL             0x0a00
#define SW_PORT_STATUS_PORTMODE_100FULL            0x0b00
#define SW_PORT_STATUS_TXPAUSED                    0x0020
#define SW_PORT_STATUS_FLOWCTRL                    0x0010

#define SW_PORT_CONTROL    0x04
#define SW_PORT_CONTROL_SAFILTERING_DISABLED       0x0000
#define SW_PORT_CONTROL_SAFILTERING_DROPONLOCK     0x4000
#define SW_PORT_CONTROL_SAFILTERING_DROPONUNLOCK   0x8000
#define SW_PORT_CONTROL_SAFILTERING_DROPTOCPU      0xc000
#define SW_PORT_CONTROL_EGRESSMODE_UNMODIFIED      0x0000
#define SW_PORT_CONTROL_EGRESSMODE_UNTAGGED        0x1000
#define SW_PORT_CONTROL_EGRESSMODE_TAGGED          0x2000
#define SW_PORT_CONTROL_HEADER                     0x0800
#define SW_PORT_CONTROL_IGMPMLDSNOOP               0x0400
#define SW_PORT_CONTROL_FRAMEMODE_NORMAL           0x0000
#define SW_PORT_CONTROL_FRAMEMODE_DSA              0x0100
#define SW_PORT_CONTROL_FRAMEMODE_PROVIDER         0x0200
#define SW_PORT_CONTROL_FRAMEMODE_ETHERTYPEDSA     0x0300
#define SW_PORT_CONTROL_VLANTUNNEL                 0x0080
#define SW_PORT_CONTROL_TAGIFBOTH                  0x0040
#define SW_PORT_CONTROL_INITIALPRI_DEFAULT         0x0000
#define SW_PORT_CONTROL_INITIALPRI_TAG             0x0010
#define SW_PORT_CONTROL_INITIALPRI_IP              0x0020
#define SW_PORT_CONTROL_INITIALPRI_TAGANDIP        0x0030
#define SW_PORT_CONTROL_EGRESSFLOOD_NOUNK          0x0000
#define SW_PORT_CONTROL_EGRESSFLOOD_NOUNKMULTICAST 0x0004
#define SW_PORT_CONTROL_EGRESSFLOOD_NOUNKUNICAST   0x0008
#define SW_PORT_CONTROL_EGRESSFLOOD_EGRESSALL      0x000c
#define SW_PORT_CONTROL_STATE_DISABLED             0x0000
#define SW_PORT_CONTROL_STATE_BLOCKLISTENING       0x0001
#define SW_PORT_CONTROL_STATE_LEARNING             0x0002
#define SW_PORT_CONTROL_STATE_FORWARDING           0x0003



#endif // _MARVELL_H
